{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e5ebbf4-04bf-42eb-b212-96c675effb64",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--------------------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a movie name (type 'exit' to quit):  avengers\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--------------------------------------------------\n",
      "Movie: Avengers: Endgame\n",
      "Genre: Action, Adventure, Drama\n",
      "--------------------------------------------------\n",
      "Recommended movies:\n",
      "1 . The Lord of the Rings: The Return of the King\n",
      "2 . The Lord of the Rings: The Two Towers\n",
      "3 . The Lord of the Rings: The Fellowship of the Ring\n",
      "--------------------------------------------------\n",
      "--------------------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a movie name (type 'exit' to quit):  avatar\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--------------------------------------------------\n",
      "Movie: Avatar\n",
      "Genre: Action, Adventure, Fantasy\n",
      "--------------------------------------------------\n",
      "Recommended movies:\n",
      "1 . Star Wars: Episode I – The Phantom Menace\n",
      "2 . Star Wars: The Last Jedi\n",
      "3 . Aquaman\n",
      "4 . Pirates of the Caribbean: Dead Man's Chest\n",
      "5 . Star Wars: Episode III – Revenge of the Sith\n",
      "--------------------------------------------------\n",
      "--------------------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a movie name (type 'exit' to quit):  aquaman\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--------------------------------------------------\n",
      "Movie: Aquaman\n",
      "Genre: Action, Adventure, Fantasy\n",
      "--------------------------------------------------\n",
      "Recommended movies:\n",
      "1 . Avatar\n",
      "2 . Star Wars: Episode I – The Phantom Menace\n",
      "3 . Star Wars: The Last Jedi\n",
      "4 . Pirates of the Caribbean: Dead Man's Chest\n",
      "5 . Star Wars: Episode III – Revenge of the Sith\n",
      "--------------------------------------------------\n",
      "--------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "import difflib\n",
    "import re\n",
    "\n",
    "# List of movies with attributes\n",
    "movies_data = {\n",
    "    'Avatar': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Titanic': {'genres': 'Drama, Romance'},\n",
    "    'Avengers: Endgame': {'genres': 'Action, Adventure, Drama'},\n",
    "    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Frozen II': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Fellowship of the Ring': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'The Dark Knight': {'genres': 'Action, Crime, Drama'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Fellowship of the Ring': {'genres': 'Action, Adventure, Drama'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Pirates of the Caribbean: On Stranger Tides': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Lion King': {'genres': 'Animation, Adventure, Drama'},\n",
    "    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Avengers: Age of Ultron': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Frozen': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Beauty and the Beast': {'genres': 'Animation, Family, Fantasy'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Alice in Wonderland': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Lord of the Rings: The Fellowship of the Ring': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "\n",
    "}\n",
    "\n",
    "# Add more movies and genres\n",
    "additional_movies = {\n",
    "     'Avatar': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Titanic': {'genres': 'Drama, Romance'},\n",
    "    'Avengers: Endgame': {'genres': 'Action, Adventure, Drama'},\n",
    "    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Frozen II': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Fellowship of the Ring': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'The Dark Knight': {'genres': 'Action, Crime, Drama'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Fellowship of the Ring': {'genres': 'Action, Adventure, Drama'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Pirates of the Caribbean: On Stranger Tides': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Lion King': {'genres': 'Animation, Adventure, Drama'},\n",
    "    'The Avengers': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Avengers: Age of Ultron': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Frozen': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Beauty and the Beast': {'genres': 'Animation, Family, Fantasy'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Alice in Wonderland': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Lord of the Rings: The Fellowship of the Ring': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'The Lion King (2019)': {'genres': 'Animation, Adventure, Drama'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Deathly Hallows – Part 2': {'genres': 'Adventure, Drama, Fantasy'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'The Lord of the Rings: The Return of the King': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: No Way Home': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Chamber of Secrets': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Jurassic Park': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Star Wars: Episode I – The Phantom Menace': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Black Panther': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Harry Potter and the Philosopher\\'s Stone': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Star Wars: The Last Jedi': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Jurassic World: Fallen Kingdom': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Beauty and the Beast (2017)': {'genres': 'Family, Fantasy, Musical'},\n",
    "    'Incredibles 2': {'genres': 'Animation, Action, Adventure'},\n",
    "    'The Fate of the Furious': {'genres': 'Action, Adventure, Crime'},\n",
    "    'Iron Man 3': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Minions': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Aquaman': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'The Lord of the Rings: The Two Towers': {'genres': 'Action, Adventure, Drama'},\n",
    "    'Spider-Man: Far From Home': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Captain Marvel': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Transformers: Dark of the Moon': {'genres': 'Action, Adventure, Sci-Fi'},\n",
    "    'Skyfall': {'genres': 'Action, Adventure, Thriller'},\n",
    "    'The Dark Knight Rises': {'genres': 'Action, Thriller'},\n",
    "    'Toy Story 4': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Alice in Wonderland (2010)': {'genres': 'Adventure, Family, Fantasy'},\n",
    "    'Pirates of the Caribbean: Dead Man\\'s Chest': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Despicable Me 3': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'The Jungle Book (2016)': {'genres': 'Adventure, Drama, Family'},\n",
    "    'Finding Dory': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Star Wars: Episode III – Revenge of the Sith': {'genres': 'Action, Adventure, Fantasy'},\n",
    "    'Harry Potter and the Order of the Phoenix': {'genres': 'Action, Adventure, Family'},\n",
    "    'Harry Potter and the Half-Blood Prince': {'genres': 'Action, Adventure, Family'},\n",
    "    'Shrek 2': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Finding Nemo': {'genres': 'Animation, Adventure, Comedy'},\n",
    "    'Harry Potter and the Goblet of Fire': {'genres': 'Adventure, Family, Fantasy'},\n",
    "\n",
    "}\n",
    "\n",
    "movies_data.update(additional_movies)\n",
    "\n",
    "# Function to recommend movies based on user preferences\n",
    "def recommend_movies(movie, movies_data):\n",
    "    # Extract genres of the input movie\n",
    "    input_genres = movies_data.get(movie, {}).get('genres', '')\n",
    "    \n",
    "    # Find movies with similar genres\n",
    "    similar_movies = []\n",
    "    for title, attributes in movies_data.items():\n",
    "        if title != movie:\n",
    "            if input_genres in attributes.get('genres', ''):\n",
    "                similar_movies.append(title)\n",
    "    \n",
    "    return similar_movies[:5]  # Return top 5 similar movies\n",
    "\n",
    "# Function to print a separator line\n",
    "def print_separator():\n",
    "    print('-' * 50)\n",
    "\n",
    "# Function to find the closest matching movie name\n",
    "def find_closest_movie(user_input, movies_data):\n",
    "    user_input_processed = re.sub(r'\\W+', '', user_input).lower()  # Remove non-alphanumeric characters and convert to lowercase\n",
    "    for movie_title in movies_data.keys():\n",
    "        movie_title_processed = re.sub(r'\\W+', '', movie_title).lower()  # Remove non-alphanumeric characters and convert to lowercase\n",
    "        if user_input_processed in movie_title_processed:\n",
    "            return movie_title\n",
    "    return None\n",
    "\n",
    "# Main loop\n",
    "while True:\n",
    "    print_separator()\n",
    "    user_movie = input(\"Enter a movie name (type 'exit' to quit): \").strip()\n",
    "\n",
    "    if user_movie.lower() == 'exit':\n",
    "        print(\"Exiting...\")\n",
    "        break\n",
    "\n",
    "    # Find the closest matching movie name\n",
    "    matched_movie = find_closest_movie(user_movie, movies_data)\n",
    "    if matched_movie:\n",
    "        user_movie = matched_movie\n",
    "    else:\n",
    "        print(\"Movie not found! Please enter a valid movie name.\")\n",
    "        continue\n",
    "\n",
    "    print_separator()\n",
    "    print(\"Movie:\", user_movie)\n",
    "    print(\"Genre:\", movies_data[user_movie]['genres'])\n",
    "\n",
    "    print_separator()\n",
    "    print(\"Recommended movies:\")\n",
    "    similar_movies = recommend_movies(user_movie, movies_data)\n",
    "    for idx, movie in enumerate(similar_movies, start=1):\n",
    "        print(idx, \".\", movie)\n",
    "\n",
    "    print_separator()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "822911f8-8c67-43e2-be29-9aa03de9f5e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "avengers\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f11ad429",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
